global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nestjs-app'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['host.docker.internal:4000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']
